version: '3'
services:
  web:
    build: .
    image: propelio
    env_file: .env
    container_name: Propelio
    restart: always
    ports:
      - "3000:3000"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
